{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Pizza Factory Latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "latency_avg{method=\"pizzaCreation\"}",
     "legendFormat": "Pizza creation "
    }
   ]
  },
  {
   "title": "Request latency ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "latency_avg{method=\"service\"}",
     "legendFormat": "Request latency "
    }
   ]
  },
  {
   "title": "System Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage{method=\"memory\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "system_usage{method=\"cpu\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "users_total{method=\"active\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Authentication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "auth_total{method=\"successful\"}",
     "legendFormat": "Successful Login"
    },
    {
     "expr": "auth_total{method=\"failed\"}",
     "legendFormat": "Failed Login"
    }
   ]
  },
  {
   "title": "HTTP requests by method/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "request_total{method=\"all\"}",
     "legendFormat": "All"
    },
    {
     "expr": "request_total{method=\"DELETE\"}",
     "legendFormat": "delete"
    },
    {
     "expr": "request_total{method=\"GET\"}",
     "legendFormat": "get"
    },
    {
     "expr": "request_total{method=\"POST\"}",
     "legendFormat": "post"
    },
    {
     "expr": "request_total{method=\"PUT\"}",
     "legendFormat": "put"
    }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(pizza_total{method=\"sold\"}[1m])",
     "legendFormat": "Pizza purchases "
    },
    {
     "expr": "pizza_total{method=\"creationFailures\"}",
     "legendFormat": "Pizza failures"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_total{method=\"revenue\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}